name: Android CI

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'composeApp/**'
      - 'android/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'gradle.properties'
  push:
    branches: [ main, develop ]
    paths:
      - 'composeApp/**'
      - 'android/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up JDK 17
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew :composeApp:assembleDebug --stacktrace

    - name: Run tests
      run: ./gradlew :composeApp:test --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
      with:
        name: debug-apk
        path: composeApp/build/outputs/apk/debug/*.apk
        retention-days: 7
