name: Deploy Android to Play Store (Reusable)

on:
  workflow_call:
    inputs:
      runner-type:
        description: 'Type of runner for identification'
        required: true
        type: string
    secrets:
      ANDROID_KEYSTORE_BASE64:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      PLAY_STORE_SERVICE_ACCOUNT_JSON:
        required: true
    outputs:
      success:
        description: 'Whether the deployment succeeded'
        value: ${{ jobs.deploy.outputs.success }}

jobs:
  deploy:
    name: Deploy Android to Play Store (${{ inputs.runner-type }})
    runs-on: ${{ fromJSON(inputs.runner-type) }}
    timeout-minutes: 5
    outputs:
      success: ${{ steps.mark-success.outputs.success }}

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up JDK 17
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Ruby for Fastlane
      uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
      with:
        ruby-version: '3.1'

    - name: Install Fastlane
      run: gem install fastlane

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore
      run: |
        mkdir -p .secrets
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > .secrets/my-release-key.jks

    - name: Create keystore.properties
      run: |
        cat > .secrets/keystore.properties << EOF
        storeFile=.secrets/my-release-key.jks
        storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
        keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
        EOF

    - name: Decode Play Store service account key
      run: |
        echo "${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}" | base64 -d > .secrets/thedeadly-app-f48493c2a133.json

    - name: Deploy to Play Store Internal Testing
      run: make deploy-testing-android

    - name: Clean up keystore
      if: always()
      run: rm -f .secrets/my-release-key.jks .secrets/keystore.properties .secrets/thedeadly-app-f48493c2a133.json

    - name: Mark success
      id: mark-success
      if: success()
      run: echo "success=true" >> $GITHUB_OUTPUT
