name: Deploy to Production

on:
  push:
    tags:
      - 'production-v*'

permissions:
  contents: write

jobs:
  promote-ios-production:
    name: Promote iOS TestFlight → App Store
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Install fastlane
      run: brew install fastlane

    - name: Decode App Store Connect API key
      run: |
        mkdir -p .secrets
        echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 -d > .secrets/AuthKey_V862XWV7WB.p8

    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/production-v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Promote TestFlight build to App Store
      run: |
        cd iosApp
        # This will need a fastlane lane that promotes the latest TestFlight build
        # For now, create a placeholder that needs manual implementation
        echo "⚠️  iOS production promotion needs manual implementation in fastlane"
        echo "Version to promote: ${{ steps.get_version.outputs.VERSION }}"
        # fastlane promote_to_appstore

    - name: Clean up
      if: always()
      run: rm -f .secrets/AuthKey_V862XWV7WB.p8

  promote-android-production:
    name: Promote Android Internal → Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up Ruby for Fastlane
      uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
      with:
        ruby-version: '3.1'

    - name: Install Fastlane
      run: gem install fastlane

    - name: Decode Play Store service account key
      run: |
        mkdir -p .secrets
        echo "${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}" | base64 -d > .secrets/thedeadly-app-f48493c2a133.json

    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/production-v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Promote Internal → Production
      run: |
        cd android
        # Promote internal → alpha → beta → production
        # For initial production release, we'll go directly from internal
        # In the future, you might want: internal → beta → production
        echo "🚀 Promoting version ${{ steps.get_version.outputs.VERSION }} to production"
        fastlane promote_beta_to_production || echo "⚠️  No beta build found, may need manual promotion"

    - name: Clean up
      if: always()
      run: rm -f .secrets/thedeadly-app-f48493c2a133.json

  create-production-release:
    name: Create GitHub Production Release
    needs: [promote-ios-production, promote-android-production]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/production-v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Extract changelog for this version
      id: changelog
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        if [ -f CHANGELOG.md ]; then
          CHANGELOG=$(awk "/## \[${VERSION}\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG=Production release $VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Production Release
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      with:
        name: "Deadly v${{ steps.get_version.outputs.VERSION }}"
        body: |
          ## 💀 Deadly v${{ steps.get_version.outputs.VERSION }}

          **Status:** Live in Production

          ### 📱 Availability
          - **iOS:** Available on the App Store
          - **Android:** Available on Google Play Store

          ### 📝 Release Notes

          ${{ steps.changelog.outputs.CHANGELOG }}

          ### 🔗 Download
          - [App Store](https://apps.apple.com/app/deadly/)
          - [Google Play](https://play.google.com/store/apps/details?id=com.grateful.deadly)
        prerelease: false
        draft: false
