name: iOS CI

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'composeApp/**'
      - 'iosApp/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'gradle.properties'
  push:
    branches: [ main, develop ]
    paths:
      - 'composeApp/**'
      - 'iosApp/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'gradle.properties'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up JDK 17
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build KMM framework for iOS Simulator
      run: ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64 --stacktrace

    - name: Build iOS app
      run: |
        cd iosApp
        xcodebuild \
          -project iosApp.xcodeproj \
          -scheme iosApp \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath ./build \
          clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
      with:
        name: ios-build
        path: iosApp/build
        retention-days: 7
